### ISSUE TITLE
A lot of errors in the log while changing wallpaper

### ISSUE THREAD

**Issue by VadimKulagin** [ifl0w/RandomWallpaperGnome3#37]
Every time there is a change of wallpaper, a lot of errors are written into the syslog.

Yesterday this led to the fact that the file syslog became a 2GB size and the system began to slow down considerably.

Because of a heap of such errors in the syslog it becomes more difficult to see something important.

Hanging is noticeable even with the usual change of wallpaper in the background during daily work.

This really irritates me and prevents me from working.

Here is an example of errors from syslog:

```
Jul  2 14:58:43 computer gnome-shell[2982]: RWG3 [INFO] >> WallpaperController :: Requesting image: https://images.unsplash.com/40/yIdlmSvfSZCyGkCkLt0P_lucaslof_2.jpg?ixlib=rb-0.3.5&q=85&fm=jpg&crop=entropy&cs=srgb&s=3baef0bfd78451f56e17708a25096bf5
Jul  2 14:58:46 computer gnome-shell[2982]: Object Meta.Background (0x55f9c625a3f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Jul  2 14:58:46 computer gnome-shell[2982]: Object Meta.Background (0x55f9c625a3f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: == Stack trace for context 0x55f9c5c7a340 ==
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #0 0x55f9c6126510 i   resource:///org/gnome/shell/ui/background.js:718 (0x7ffb0840f450 @ 22)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #1 0x7ffe14902030 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7ffb086d3b38 @ 54)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #2 0x7ffe14902180 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7ffb086d3bc0 @ 1626)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #3 0x7ffe14902230 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7ffb086d3c48 @ 100)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #4 0x7ffe149022c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7ffb086d3cd0 @ 10)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #5 0x7ffe149023b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffb086d3230 @ 386)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #6 0x7ffe14902460 b   resource:///org/gnome/shell/ui/tweener.js:245 (0x7ffb086cf808 @ 159)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #7 0x7ffe149024c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffb086b5de0 @ 71)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #8 0x7ffe14902560 b   resource:///org/gnome/shell/ui/tweener.js:220 (0x7ffb086cf780 @ 15)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: == Stack trace for context 0x55f9c5c7a340 ==
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #0 0x55f9c6126510 i   resource:///org/gnome/shell/ui/background.js:718 (0x7ffb0840f450 @ 22)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #1 0x7ffe14902030 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7ffb086d3b38 @ 54)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #2 0x7ffe14902180 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7ffb086d3bc0 @ 1626)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #3 0x7ffe14902230 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7ffb086d3c48 @ 100)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #4 0x7ffe149022c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7ffb086d3cd0 @ 10)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #5 0x7ffe149023b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffb086d3230 @ 386)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #6 0x7ffe14902460 b   resource:///org/gnome/shell/ui/tweener.js:245 (0x7ffb086cf808 @ 159)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #7 0x7ffe149024c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffb086b5de0 @ 71)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #8 0x7ffe14902560 b   resource:///org/gnome/shell/ui/tweener.js:220 (0x7ffb086cf780 @ 15)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: == Stack trace for context 0x55f9c5c7a340 ==
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #0 0x55f9c6126598 i   resource:///org/gnome/shell/ui/background.js:718 (0x7ffb0840f450 @ 22)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #1 0x55f9c6126510 i   resource:///org/gnome/shell/ui/tweener.js:113 (0x7ffb086c7e68 @ 37)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #2 0x7ffe14902030 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7ffb086d3b38 @ 54)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #3 0x7ffe14902180 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7ffb086d3bc0 @ 1626)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #4 0x7ffe14902230 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7ffb086d3c48 @ 100)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #5 0x7ffe149022c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7ffb086d3cd0 @ 10)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #6 0x7ffe149023b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffb086d3230 @ 386)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #7 0x7ffe14902460 b   resource:///org/gnome/shell/ui/tweener.js:245 (0x7ffb086cf808 @ 159)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #8 0x7ffe149024c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffb086b5de0 @ 71)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #9 0x7ffe14902560 b   resource:///org/gnome/shell/ui/tweener.js:220 (0x7ffb086cf780 @ 15)
Jul  2 14:58:46 computer gnome-shell[2982]: Object Meta.Background (0x55f9c625a3f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: == Stack trace for context 0x55f9c5c7a340 ==
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #0 0x55f9c6126598 i   resource:///org/gnome/shell/ui/background.js:718 (0x7ffb0840f450 @ 22)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #1 0x55f9c6126510 i   resource:///org/gnome/shell/ui/tweener.js:113 (0x7ffb086c7e68 @ 37)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #2 0x7ffe14902030 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7ffb086d3b38 @ 54)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #3 0x7ffe14902180 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7ffb086d3bc0 @ 1626)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #4 0x7ffe14902230 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7ffb086d3c48 @ 100)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #5 0x7ffe149022c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7ffb086d3cd0 @ 10)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #6 0x7ffe149023b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffb086d3230 @ 386)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #7 0x7ffe14902460 b   resource:///org/gnome/shell/ui/tweener.js:245 (0x7ffb086cf808 @ 159)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #8 0x7ffe149024c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffb086b5de0 @ 71)
Jul  2 14:58:46 computer org.gnome.Shell.desktop[2982]: #9 0x7ffe14902560 b   resource:///org/gnome/shell/ui/tweener.js:220 (0x7ffb086cf780 @ 15)
Jul  2 14:58:46 computer gnome-shell[2982]: Object Meta.Background (0x55f9c7ffa8f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
```

Here is the configuration of my system:
OS: Ubuntu 18.04 LTS (bionic)
GNOME Shell 3.28.1
CPU: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
RAM: 8GB

**Comment by ifl0w** [comment]
This probably has something to do with the animation of the icon during the download, but I am not sure. I'll investigate it as soon as possible.

**Comment by ifl0w** [comment]
It seems that this is an upstream bug in the gnome-shell and can't be fixed in this extension.
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1

The logs are inserted if the wallpaper of the desktop is changed. Therefore you might want to disable the hover preview in the settings to reduce the number of logs. Be aware that this will not really fix the problem.

Hopefully, this will be fixed in the next gnome release.

**Comment by VadimKulagin** [comment]
The hover preview is already disabled.
But thanks for the answer.

**Comment by ifl0w** [comment]
I uploaded some fixes yesterday and was wondering if this problem still occurs? Otherwise, I'd close this issue in the next week or so.

**Comment by VadimKulagin** [comment]
@ifl0w, unfortunately, thousands of these errors are still written to the log.

**Comment by ifl0w** [comment]
Ok, I am sorry the inconvenience.

In the discussion of the link I provided, it is mentioned that parts of the bug got fixed in gnome 3.30. 
So, an upgrade could resolve the issue for you if that is an option.

**Comment by VadimKulagin** [comment]
Well, I will wait for the Gnome update.
